databases:
  - name: db.example.com
    databaseName: akkoma
    plan: starter # $7/mo - required for persistent database
    ipAllowList: [] # only allow internal connections
services:
  - name: akkoma.example.com
    type: web
    env: docker
    repo: https://github.com/tamarou/akkoma-render.git # change to your repo
    autoDeploy: false
    domains:
      - akkoma.example.com # change to your custom domain
    envVars:
      - key: DOMAIN
        value: akkoma.example.com # must match the value in domains
      - key: DB_HOST
        fromDatabase:
          name: akkoma
          property: host
      - key: DB_USER
        fromDatabase:
          name: akkoma
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: akkoma
          property: password
