services:
  - type: web
    name: akkoma
    env: docker
    repo: https://github.com/tamarou/akkoma-render.git # optional
    autoDeploy: false
    envVars:
      - key: DOMAIN
        value: akkoma.example.com
      - key: DB_HOST
        fromDatabase:
          name: akkoma
          property: host
      - key: DB_USER
        fromDatabase:
          name: akkoma
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: akkoma
          property: password
databases:
  - name: akkoma
    databaseName: akkoma
    plan: starter # $7/mo - required for persistent database
    ipAllowList: [] # only allow internal connections
